---
title: Comedy Ottawa
baseURL: "/"
params:
  color_scheme: light
  accent_color: pink
  header:
    title: 'Comedy Ottawa '
    has_nav: true
    logo_img: "/images/comedyottawa-logo_colour.jpg"
  footer:
    content: 'made by '
    links:
    - text: "@lowenergycomic"
      url: https://www.instagram.com/lowenergycomic/
      new_window: true
    has_social: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
